version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    ports:
    - "5432"

volumes:
  bundle:
  data:
